version: "3.9"
services:
  my-app:
    build:
      context: ./my-app
      dockerfile: ./Dockerfile
    environment:
      - NODE_ENV=development
      - BACKEND_HOST=backend
      - BACKEND_PORT=3000
      - BACKEND_URL='http://'+BACKEND_HOST+':'+BACKEND_PORT
      - BACKEND_ANALYZE=true
    ports:
      - "3002:3002"
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"

