version: "3.9"
services:
  my-app:
    build:
      context: ./my-app
      dockerfile: ./Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - "3002:3002"
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"

