version: "3.9"
services:
  frontend:
    build:
      # context: .
      dockerfile: ./my-app/Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - "3002:3002"
    depends_on:
      - backend
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=vehicle4you
    ports:
      - "5432:5432"