import Head from "next/head";
import Layout from "../../components/layout";
import styles from "@/styles/searchcar.module.css";
import { Row, Col, Spinner } from "react-bootstrap";
import Link from "next/link";
import { FaSignInAlt } from "react-icons/fa";
import { BiSearchAlt2 } from "react-icons/fa";

import React, { useState } from "react";
import Dropdown from "react-bootstrap/Dropdown";
import Form from "react-bootstrap/Form";

// The forwardRef is important!!
// Dropdown needs access to the DOM node in order to position the Menu
const CustomToggle = React.forwardRef(({ children, onClick }, ref) => (
  <a
    href=""
    ref={ref}
    onClick={(e) => {
      e.preventDefault();
      onClick(e);
    }}
  >
    {children}
    &#x25bc;
  </a>
));

// forwardRef again here!
// Dropdown needs access to the DOM of the Menu to measure it
const CustomMenu = React.forwardRef(
  ({ children, style, className, "aria-labelledby": labeledBy }, ref) => {
    const [value, setValue] = useState("");

    return (
      <div
        ref={ref}
        style={style}
        className={className}
        aria-labelledby={labeledBy}
      >
        <Form.Control
          autoFocus
          className="mx-3 my-2 w-auto"
          placeholder="Type to filter..."
          onChange={(e) => setValue(e.target.value)}
          value={value}
        />
        <ul className="list-unstyled">
          {React.Children.toArray(children).filter(
            (child) =>
              !value || child.props.children.toLowerCase().startsWith(value)
          )}
        </ul>
      </div>
    );
  }
);

export default function SearchCar() {
  let [username, setUsername] = useState("");
  let [pw, setPw] = useState("");
  let [role, setRole] = useState("");

  let [invalid, setInvalid] = useState("");

  let [loading, setLoading] = useState(false);

  async function handleSubmit(event: Event) {
    event.preventDefault();

    setLoading(true);

    const res = await fetch("/api/signin", {
      headers: {
        "Content-Type": "application/json",
      },
      method: "POST",
      body: JSON.stringify({ username: username, password: pw, role }),
    }).then(async (res) => {
      const result = await res.json();

      setLoading(false);

      if (res.status == 400) {
        setUsername("");
        setPw("");
        setRole("");
        setInvalid(result.message);
      } else {
        setInvalid("");
        alert("logging in");
      }
    });
  }

  return (
    <>
      <Head>
        <title>หน้าหลัก-VEHICLE4U</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <div className={`${styles.main}`}>
          <Row style={{ height: "100vh", width: "100%" }}>
            <Col
              sm={12}
              lg={20}
              className="d-flex justify-content-center align-items-center"
            >
              <div
                className={`${styles.form_container} justify-content-center d-flex align-items-center`}
              >
                <form style={{ width: "90%" }}>
                  <h5 className={`p-2 ${styles.head} mb-1 text-center`}>
                    บริการเช่ารถ
                  </h5>

                  <br />
                  <br />

                  <Row>
                    <Col sm={12} lg={6}>
                      <Row className={`p-3 ${styles.role} mb-1 text-center`}>
                        <Col
                          sm={12}
                          lg={5}
                          style={{ borderRight: "1px solid black" }}
                        >
                          <h6>จังหวัด</h6>
                          <Dropdown>
                            <Dropdown.Toggle
                              as={CustomToggle}
                              id="dropdown-custom-components"
                            >
                              กรุงเทพมหานคร
                            </Dropdown.Toggle>

                            <Dropdown.Menu as={CustomMenu}>
                              <Dropdown.Item eventKey="1">
                                กรุงเทพมหานคร
                              </Dropdown.Item>
                              <Dropdown.Item eventKey="2">
                                นนทบุรี
                              </Dropdown.Item>
                              <Dropdown.Item eventKey="3">
                                ปทุมธานี
                              </Dropdown.Item>
                            </Dropdown.Menu>
                          </Dropdown>
                        </Col>
                        <Col sm={12} lg={7}>
                          <h6>สถานที่ส่งรับ-รถคืน</h6>
                          <Dropdown>
                            <Dropdown.Toggle
                              as={CustomToggle}
                              id="dropdown-custom-components"
                            >
                              คณะวิศวกรรมศาสตร์ จุฬาฯ
                            </Dropdown.Toggle>

                            <Dropdown.Menu as={CustomMenu}>
                              <Dropdown.Item eventKey="1">
                                คณะวิศวกรรมศาสตร์ จุฬาฯ
                              </Dropdown.Item>
                              <Dropdown.Item eventKey="2">
                                คณะอักษรศาสตร์ จุฬาฯ
                              </Dropdown.Item>
                              <Dropdown.Item eventKey="3">
                                คณะบัญชีศาสตร์ จุฬาฯ
                              </Dropdown.Item>
                            </Dropdown.Menu>
                          </Dropdown>
                        </Col>
                      </Row>
                    </Col>

                    <Col sm={12} lg={4}>
                      <div className={`p-2 ${styles.role} mb-3 text-center`}>
                        <Row>
                          <Col>วัน-เวลารับรถ</Col>
                          <Col>
                            
                          </Col>
                        </Row>
                        <Row>
                          <Col>วัน-เวลาส่งรถ</Col>
                          <Col></Col>
                        </Row>
                      </div>
                    </Col>

                    <Col sm={12} lg={2}>
                      <button
                        type="button"
                        onClick={(event: any) => handleSubmit(event)}
                        className={`${styles.searchbtn}`}
                      >
                        {loading && (
                          <>
                            <Spinner
                              className={`${styles.spinner}`}
                              animation="border"
                              variant="primary"
                            />{" "}
                          </>
                        )}
                        <b>ค้นหา</b>
                      </button>
                    </Col>
                  </Row>
                </form>
              </div>
            </Col>
          </Row>
        </div>
      </Layout>
    </>
  );
}
