import Head from "next/head";
import Layout from "../../components/layout";
import styles from "@/styles/searchcar.module.css";
import { Row, Col, Spinner } from "react-bootstrap";

import React, { useState } from "react";
import Dropdown from "react-bootstrap/Dropdown";
import Form from "react-bootstrap/Form";
import { BiSearchAlt } from "react-icons/bi";

import DatePicker from "react-datepicker";
import "react-datepicker/dist/react-datepicker.css";

// The forwardRef is important!!
// Dropdown needs access to the DOM node in order to position the Menu
const CustomToggle = React.forwardRef(({ children, onClick }, ref) => (
  <a
    href=""
    ref={ref}
    onClick={(e) => {
      e.preventDefault();
      onClick(e);
    }}
  >
    {children}
    &#x25bc;
  </a>
));

// forwardRef again here!
// Dropdown needs access to the DOM of the Menu to measure it

const CustomMenu = React.forwardRef(
  ({ children, style, className, "aria-labelledby": labeledBy }, ref) => {
    const [value, setValue] = useState("");

    return (
      <div
        ref={ref}
        style={style}
        className={className}
        aria-labelledby={labeledBy}
      >
        <Form.Control
          autoFocus
          className="mx-3 my-2 w-auto"
          placeholder="Type to filter..."
          onChange={(e) => setValue(e.target.value)}
          value={value}
        />
        <ul className="list-unstyled">
          {React.Children.toArray(children).filter(
            (child) =>
              !value || child.props.children.toLowerCase().startsWith(value)
          )}
        </ul>
      </div>
    );
  }
);

export default function SearchCar() {
  const today = new Date();

  const tomorrow = new Date();
  tomorrow.setDate(tomorrow.getDate() + 1);

  const [startDate1, setStartDate1] = useState(today);
  const [startDate2, setStartDate2] = useState(tomorrow);

  let [loading, setLoading] = useState(false);

  return (
    <>
      <Head>
        <title>หน้าหลัก-VEHICLE4U</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={`${styles.main}`}>
        <Row style={{ height: "100vh", width: "100%" }}>
          <Col
            sm={12}
            lg={20}
            className="d-flex justify-content-center align-items-center"
          >
            <div
              className={`${styles.form_container} justify-content-center d-flex align-items-center`}
            >
              <form style={{ width: "90%" }}>
                <h5 className={` ${styles.head} mb-1 text-center`}>
                  บริการเช่ารถ
                </h5>

                <br />
                <br />

                <Row>
                  <Col sm={12} lg={6}>
                    <Row className={`p-3 ${styles.role} mb-1 text-center`}>
                      <Col
                        sm={12}
                        lg={4}
                        style={{ borderRight: "1px solid black" }}
                      >
                        <h6>จังหวัด</h6>
                        <Dropdown>
                          <Dropdown.Toggle
                            as={CustomToggle}
                            id="dropdown-custom-components"
                          >
                            กรุงเทพมหานคร
                          </Dropdown.Toggle>

                          <Dropdown.Menu as={CustomMenu} >
                            <Dropdown.Item eventKey="1">
                              กรุงเทพมหานคร
                            </Dropdown.Item>
                            <Dropdown.Item eventKey="2">นนทบุรี</Dropdown.Item>
                            <Dropdown.Item eventKey="3">ปทุมธานี</Dropdown.Item>
                          </Dropdown.Menu>
                        </Dropdown>
                      </Col>
                      <Col
                        sm={12}
                        lg={4}
                        style={{ borderRight: "1px solid black" }}
                      >
                        <h6>ยี่ห้อรถ</h6>
                        <Dropdown>
                          <Dropdown.Toggle
                            as={CustomToggle}
                            id="dropdown-custom-components"
                          >
                            Toyota Altis
                          </Dropdown.Toggle>

                          <Dropdown.Menu as={CustomMenu}>
                            <Dropdown.Item eventKey="1">
                              Toyota Altis
                            </Dropdown.Item>
                            <Dropdown.Item eventKey="2">
                              Toyota Yaris
                            </Dropdown.Item>
                            <Dropdown.Item eventKey="3">
                              Ford Ranger Raptor
                            </Dropdown.Item>
                          </Dropdown.Menu>
                        </Dropdown>
                      </Col>
                      

                      <Col
                        sm={12}
                        lg={4}
                      >
                        <h6>จำนวนผู้โดยสาร</h6>
                        <Dropdown>
                          <Dropdown.Toggle
                            as={CustomToggle}
                            id="dropdown-custom-components"
                          >
                            1
                          </Dropdown.Toggle>

                          <Dropdown.Menu as={CustomMenu}>
                            <Dropdown.Item eventKey="1">
                              1
                            </Dropdown.Item>
                            <Dropdown.Item eventKey="2">
                              2
                            </Dropdown.Item>
                            <Dropdown.Item eventKey="3">
                              3
                            </Dropdown.Item>
                          </Dropdown.Menu>
                        </Dropdown>
                      </Col>
                      



                    </Row>
                  </Col>

                  <Col sm={12} lg={4}>
                    <div className={`p-2 ${styles.role} mb-3 text-center`}>
                      <Row className={`${styles.p1}`}>
                        <Col>วัน-เวลารับรถ</Col>
                        <Col>
                          <DatePicker
                            className={`${styles.picker}`}
                            selected={startDate1}
                            onChange={(date1) => setStartDate1(date1)}
                            dateFormat="dd/MM/yyyy"
                          />
                        </Col>
                      </Row>
                      <Row className={`${styles.p2}`}>
                        <Col>วัน-เวลาส่งรถ</Col>
                        <Col>
                          <DatePicker
                            className={`${styles.picker}`}
                            selected={startDate2}
                            onChange={(date2) => setStartDate2(date2)}
                            dateFormat="dd/MM/yyyy"
                          />
                        </Col>
                      </Row>
                    </div>
                  </Col>

                  <Col sm={12} lg={2}>
                    <button type="button" className={`${styles.searchbtn}`}>
                      {loading && (
                        <>
                          <Spinner
                            className={`${styles.spinner}`}
                            animation="border"
                            variant="primary"
                          />{" "}
                        </>
                      )}
                      <BiSearchAlt size={60} />
                    </button>
                  </Col>
                </Row>
              </form>
            </div>
          </Col>
        </Row>
      </div>
    </>
  );
}
