version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    container_name: database-se2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_1
    expose:
      - "5432"
      - POSTGRES_USER = postgres
      - POSTGRES_PASSWORD = postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
